name: bmi_app
description: A simple BMI calculator app

environment:
  sdk: '^3.3.0'

dependencies:
  flutter:
    sdk: flutter
  pretty_gauge: ^1.0.0
  share_plus: ^4.0.8
  flutter_3d_choice_chip: ^0.1.4
  page_transition: ^2.0.9
  swipeable_button_view: ^0.0.1
  cupertino_icons: ^1.0.8

flutter:
  assets:
    - assets/images/man.png
    - assets/images/woman.png
